CONDICIONALES.JS

var saludar="si";
 
if(saludar=="si"){
    console.log("Hola, soy un condicional simple");
}
//segundo punto

var x=20;
 
if(x<=20){
    console.log("La condición es verdadera");
}

//tercer punto

var edad=18;
 
if(edad>=18){	
    console.log("Bienvenido, puede ingresar");
}else{

    console.log("Lo siento, no tiene edad suficiente para entrar aquí");
}

//cuarto punto

var numero1 = 5;
var numero2 = 8;
 
if(numero1<numero2) {
  console.log("numero1 no es mayor que numero2");
}
if(numero2> 0) {
  console.log("numero2 es positivo");
}
if(numero1< 0 || numero1 1=0) {
  console.log("numero1 es negativo o distinto de cero");
}
if(numero1 + 1 < numero2) {
  console.log("Incrementar en 1 unidad el valor de numero1 no lo hace mayor o igual que numero2");
}

//quinto punto

var numerito = 100;
 
if( numerito < 50 ) {
  console.log("numerito sí es estrictamente menor que 50");
}else if( numerito > 50 && numerito < 80) {
  console.log("numerito sí está entre 50 y 80");
}else if(numerito > 80 && ! (numerito>=100)) {
  console.log("numerito es mayor que 80 pero no mayor ni igual a 100");
}else if(numerito == 100) {
  console.log("numerito es igual a 100");
}else{
    console.log("numerito es estrictamente mayor a 100");
}

//sexto punto

numerito = 90

//septimo punto

numerito = 65

//octavo punto

numerito =100

//punto nueve 
var hoy="jueves";
if(hoy == "jueves")
console.log("puede ir al poli");
console.log("no puede ir al poli")

//punto diez
var x=10
var y=5
 if(y==0)
console.log("no se puede dividir");
}else if 
  console.log(x/y);

  //punto  once 
  var quedia;
  if(quedia=="lunes"){
      console.log("arroz con pollo");
}else if (quedia== "martes"){
    console.log("cguleta de cerdo/pollo");
}else if (quedia== "miercoles"){
  console.log("frijoles");
}else if  (quedia== "jueves"){
  console.log ("sancocho de pescado");
}else if (quedia== "viernes"){
   console.log("bandeja paisa");
}else if (quedia== "sabado "){
  console.log("ajiaco");
}else if (quedia== "domingo"){
   console.log("samcochode gallina");
}

//punto12

 


